## Server Properties
server:
  port: 7986

app:
  jwtSecret: 9a02115a835ee03d5fb83cd8a468ea33e4090aaaec87f53c9fa54512bbef4db8dc656c82a315fa0c785c08b0134716b81ddcd0153d2a7556f2e154912cf5675f
  jwtExpirationInMs: 604800000
  cors:
    allowedOrigins: http://localhost:3000

spring:
  ## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/poll?useSSL=false&serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false
    username: root
    password: Kabi123.
  jpa:
    show-sql: true
    ## Hibernate Properties
    hibernate:
      ddl-auto: update
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  sql:
    init:
      # Initialize the datasource with available DDL and DML scripts
      mode: always
  ## Jackson Properties
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

## Hibernate Logging
logging:
  level:
    org.hibernate.SQL: DEBUG